import React from 'react';

export const LegalDisclaimer: React.FC = () => {
  return (
    <div className="mt-8 p-4 bg-slate-800/50 border border-slate-700 rounded-lg text-xs text-slate-400">
      <p className="font-semibold mb-1 text-slate-300">DISCLAIMER:</p>
      <p>
        This analysis is generated by Artificial Intelligence for informational purposes only and does not constitute binding legal advice. 
        While based on Kenyan, US, and UK legal principles, it should not replace the counsel of a qualified attorney. 
        Please consult with Khalwale & Co Advocates for final contract vetting.
      </p>
    </div>
  );
};